// Use the compiled ESM bundle: Node on Vercel cannot resolve Vite's source aliases.
// @ts-ignore Generated by npm run build before Vercel packages this function.
export { default } from '../dist/server.bundle.mjs';
